services:
  todo-app:
    image: todo-app:latest
    container_name: todo-app
    restart: "no"
  nginx:
    image: nginx:stable
    container_name: xnign
    ports:
      - 80:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: "no"